services:
  ms-stock-app:
    image: evandroig/ms-stock:latest
    networks:
      - "ms-stock-network"
    ports:
      - "8080:8080"
    links:
      - "mongodb:servicedb"
    depends_on:
      - "mongodb"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/ms-stock
  mongodb:
    networks:
      - "ms-stock-network"
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    image: mongo:latest
networks:
  ms-stodk-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"