server:
  port: 8083
spring:
  data:
    mongodb:
      initialization-mode: always
      uri: mongodb://localhost:27017/ms-stock
  liquibase:
    change-log:
      classpath: db-json/master.json
    enabled: true